// ------------------------------------------------------------------------
// File:    06.1_dax_measures.dax
// Purpose: All DAX measures for Retail Analytics Portfolio Power BI report
//          Saved here for documentation and version control
//          Note: Entered manually as there is no direct import ability
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// CORE SALES MEASURES
// ------------------------------------------------------------------------

// Total sales from monthly aggregated fact table
Total Sales = SUM('monthly sales'[sales])

// Total prior year sales for YOY comparison
Total Sales PY = SUM('monthly sales'[sales py])

// Year over year sales variance in absolute terms
Sales YOY $ = [Total Sales] - [Total Sales PY]

// Year over year sales variance as percentage
// DIVIDE used instead of / to handle zero denominator gracefully
Sales YOY % = DIVIDE([Sales YOY $], [Total Sales PY], 0)

// ------------------------------------------------------------------------
// CORE VOLUME MEASURES
// ------------------------------------------------------------------------

// Total volume (units) from monthly aggregated fact table
Total Qty = SUM('monthly sales'[qty])

// Total prior year volume for YOY comparison
Total Qty PY = SUM('monthly sales'[qty py])

// Year over year volume variance in absolute terms
Qty YOY $ = [Total Qty] - [Total Qty PY]

// Year over year volume variance as percentage
Qty YOY % = DIVIDE([Qty YOY $], [Total Qty PY], 0)

// ------------------------------------------------------------------------
// PRICING MEASURES
// ------------------------------------------------------------------------

// Average price per unit - current year
// Calculated as sales divided by volume to avoid storing price directly
Avg Price = DIVIDE([Total Sales], [Total Qty], 0)

// Average price per unit - prior year
Avg Price PY = DIVIDE([Total Sales PY], [Total Qty PY], 0)

// Year over year average price change as percentage
Avg Price YOY % = DIVIDE([Avg Price] - [Avg Price PY], [Avg Price PY], 0)

// ------------------------------------------------------------------------
// STORE PERFORMANCE MEASURES
// ------------------------------------------------------------------------

// Count of distinct stores in current filtered context
Store Count = DISTINCTCOUNT('monthly sales'[store_key])

// Count of existing stores only (excludes new stores)
// Used for prior year comparison to ensure apples-to-apples
// new store = FALSE means store existed prior to current period
Store Count PY = 
CALCULATE(
    DISTINCTCOUNT('monthly sales'[store_key]),
    store[new store] = FALSE()
)

// Sales per store - current year, all stores
Sales per Store = DIVIDE([Total Sales], [Store Count], 0)

// Sales per store - prior year, existing stores only
// Excludes new stores to show true same-store performance
Sales per Store PY = DIVIDE([Total Sales PY], [Store Count PY], 0)

// ------------------------------------------------------------------------
// MARKET SHARE MEASURES
// Note: Share measures calculate within whatever filter context is active
//       ALL() removes the specific dimension filter to get total
//       allowing share % to be calculated against the full market
// ------------------------------------------------------------------------

// Category sales share - what % of total sales does selected category represent
Category Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(product[category])),
    0
)

// Brand sales share - what % of total sales does selected brand represent
Brand Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(product[brand])),
    0
)

// Supplier sales share - what % of total sales does selected supplier represent
Supplier Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(product[supplier])),
    0
)

// Package sales share - what % of total sales does selected package represent
Package Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(product[package])),
    0
)

// Pack size type share - Single Serve vs Large Single vs Multipack
// Useful for understanding how pack format trends are shifting
Pack Size Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(product[pack size type])),
    0
)

// Regional sales share - what % of total sales does selected region represent
Region Sales Share % = 
DIVIDE(
    [Total Sales],
    CALCULATE([Total Sales], ALL(store[region])),
    0
)

// ------------------------------------------------------------------------
// FIELD PARAMETERS (created via Modeling > New Parameter > Fields)
// Note: These are auto-generated by Power BI and stored as DAX tables
//       Documented here for reference only
// ------------------------------------------------------------------------

// Metric parameter - allows user to switch between Sales and Volume
// Sales/Volume toggle in filter strip
Metric = {
    ("Sales", NAMEOF('_Measures'[Total Sales]), 0),
    ("Volume", NAMEOF('_Measures'[Total Qty]), 1)
}

// Focus parameter - allows user to switch chart dimension
// Controls what attribute the main visual breaks down by
Focus = {
    ("Category", NAMEOF('product'[category]), 0),
    ("Sub-Category", NAMEOF('product'[subcategory]), 1),
    ("Supplier", NAMEOF('product'[supplier]), 2),
    ("Brand", NAMEOF('product'[brand]), 3),
    ("Pack Size Type", NAMEOF('product'[pack size type]), 4),
    ("Package", NAMEOF('product'[package]), 5),
    ("Product Desc.", NAMEOF('product'[description]), 6),
    ("Store Type", NAMEOF('store'[store type]), 7),
    ("Region", NAMEOF('store'[region]), 8),
    ("State", NAMEOF('store'[state]), 9),
    ("City", NAMEOF('store'[city]), 10),
    ("Store Name", NAMEOF('store'[store name]), 11)
}
```

---

**Commit message:**
```
Add sort column script and DAX measures documentation

- 04.7: quarter_sort column added to mart.dim_date for Power BI 
  chronological quarter ordering
- 06.1: All DAX measures documented with comments including
  core sales, volume, pricing, store performance, share measures
  and field parameters (Metric and Focus)